export const DEFAULT_EXERCISE_NAMES = [
  'Barbell Bench Press',
  'Incline Dumbbell Press',
  'Overhead Press',
  'Lateral Raise',
  'Pull-Up',
  'Lat Pulldown',
  'Barbell Row',
  'Seated Cable Row',
  'Back Squat',
  'Romanian Deadlift',
  'Leg Press',
  'Walking Lunge',
  'Leg Extension',
  'Leg Curl',
  'Hip Thrust',
  'Standing Calf Raise',
  'Barbell Curl',
  'Hammer Curl',
  'Triceps Pushdown',
  'Skull Crusher',
  'Cable Crunch',
  'Plank',
] as const
