export const DEFAULT_EXERCISE_NAMES = [
  // Chest
  'Barbell Bench Press',
  'Paused Barbell Bench Press',
  'Close-Grip Bench Press',
  'Wide-Grip Bench Press',
  'Decline Barbell Bench Press',
  'Smith Machine Bench Press',
  'Machine Chest Press',
  'Plate-Loaded Chest Press',
  'Single-Arm Machine Chest Press',
  'Incline Barbell Bench Press',
  'Incline Dumbbell Press',
  'Incline Smith Machine Press',
  'Incline Machine Chest Press',
  'Decline Dumbbell Press',
  'Flat Dumbbell Press',
  'Neutral-Grip Dumbbell Press',
  'Dumbbell Floor Press',
  'Guillotine Press',
  'Cable Chest Press',
  'Standing Cable Chest Press',
  'Single-Arm Cable Chest Press',
  'High-to-Low Cable Fly',
  'Low-to-High Cable Fly',
  'Cable Fly',
  'Single-Arm Cable Fly',
  'Pec Deck Fly',
  'Machine Fly',
  'Dumbbell Fly',
  'Incline Dumbbell Fly',
  'Decline Dumbbell Fly',
  'Svend Press',
  'Push-Up',
  'Weighted Push-Up',
  'Deficit Push-Up',
  'Incline Push-Up',
  'Decline Push-Up',
  'Chest Dip',
  'Weighted Dip',
  // Shoulders
  'Overhead Press',
  'Seated Barbell Overhead Press',
  'Seated Dumbbell Overhead Press',
  'Arnold Press',
  'Push Press',
  'Behind-the-Neck Press',
  'Machine Shoulder Press',
  'Smith Machine Overhead Press',
  'Landmine Press',
  'Single-Arm Landmine Press',
  'Cable Shoulder Press',
  'Dumbbell Lateral Raise',
  'Lateral Raise',
  'Seated Lateral Raise',
  'Cable Lateral Raise',
  'Single-Arm Cable Lateral Raise',
  'Machine Lateral Raise',
  'Lean-Away Lateral Raise',
  'Dumbbell Front Raise',
  'Cable Front Raise',
  'Plate Front Raise',
  'Barbell Front Raise',
  'Rear Delt Fly',
  'Reverse Pec Deck',
  'Bent-Over Dumbbell Rear Delt Fly',
  'Cable Rear Delt Fly',
  'Face Pull',
  'Upright Row',
  'Cable Upright Row',
  'Barbell Shrug',
  'Dumbbell Shrug',
  'Machine Shrug',
  'Smith Machine Shrug',
  // Back
  'Pull-Up',
  'Weighted Pull-Up',
  'Assisted Pull-Up',
  'Chin-Up',
  'Weighted Chin-Up',
  'Assisted Chin-Up',
  'Neutral-Grip Pull-Up',
  'Wide-Grip Pull-Up',
  'Close-Grip Pull-Up',
  'Lat Pulldown',
  'Wide-Grip Lat Pulldown',
  'Close-Grip Lat Pulldown',
  'Underhand Lat Pulldown',
  'Single-Arm Lat Pulldown',
  'Machine Pulldown',
  'Straight-Arm Pulldown',
  'Barbell Row',
  'Pendlay Row',
  'Yates Row',
  'Dumbbell Row',
  'Single-Arm Dumbbell Row',
  'Chest-Supported Dumbbell Row',
  'Chest-Supported T-Bar Row',
  'T-Bar Row',
  'Landmine Row',
  'Meadows Row',
  'Seated Cable Row',
  'Close-Grip Seated Cable Row',
  'Wide-Grip Seated Cable Row',
  'Single-Arm Seated Cable Row',
  'Machine Row',
  'Iso-Lateral Row Machine',
  'Hammer Strength Row',
  'Inverted Row',
  'Rack Pull',
  'Snatch-Grip Rack Pull',
  'Deadlift',
  'Conventional Deadlift',
  'Sumo Deadlift',
  'Trap Bar Deadlift',
  'Deficit Deadlift',
  'Romanian Deadlift',
  'Dumbbell Romanian Deadlift',
  'Stiff-Leg Deadlift',
  'Good Morning',
  'Back Extension',
  '45 Degree Back Extension',
  'Reverse Hyperextension',
  // Legs and glutes
  'Back Squat',
  'Front Squat',
  'High-Bar Back Squat',
  'Low-Bar Back Squat',
  'Paused Back Squat',
  'Box Squat',
  'Goblet Squat',
  'Zercher Squat',
  'Hack Squat',
  'Machine Hack Squat',
  'Belt Squat',
  'Smith Machine Squat',
  'Smith Machine Front Squat',
  'Safety Bar Squat',
  'Split Squat',
  'Bulgarian Split Squat',
  'Front Foot Elevated Split Squat',
  'Rear Foot Elevated Split Squat',
  'Reverse Lunge',
  'Walking Lunge',
  'Forward Lunge',
  'Lateral Lunge',
  'Curtsy Lunge',
  'Dumbbell Step-Up',
  'Barbell Step-Up',
  'Machine Step-Up',
  'Leg Press',
  'Single-Leg Leg Press',
  'Horizontal Leg Press',
  '45 Degree Leg Press',
  'V-Squat Machine',
  'Pendulum Squat Machine',
  'Leg Extension',
  'Single-Leg Extension',
  'Sissy Squat',
  'Romanian Chair Squat',
  'Leg Curl',
  'Lying Leg Curl',
  'Seated Leg Curl',
  'Standing Leg Curl',
  'Single-Leg Curl',
  'Nordic Hamstring Curl',
  'Glute Ham Raise',
  'Cable Pull-Through',
  'Hip Thrust',
  'Barbell Glute Bridge',
  'Single-Leg Hip Thrust',
  'Machine Hip Thrust',
  'Smith Machine Hip Thrust',
  'Cable Kickback',
  'Machine Glute Kickback',
  'Cable Hip Abduction',
  'Machine Hip Abduction',
  'Machine Hip Adduction',
  'Frog Pump',
  // Calves and tibialis
  'Standing Calf Raise',
  'Seated Calf Raise',
  'Leg Press Calf Raise',
  'Smith Machine Calf Raise',
  'Single-Leg Calf Raise',
  'Donkey Calf Raise',
  'Tibialis Raise',
  'Machine Tibialis Raise',
  // Biceps
  'Barbell Curl',
  'EZ Bar Curl',
  'Dumbbell Curl',
  'Alternating Dumbbell Curl',
  'Incline Dumbbell Curl',
  'Spider Curl',
  'Preacher Curl',
  'Machine Preacher Curl',
  'Cable Curl',
  'Bayesian Cable Curl',
  'High Cable Curl',
  'Reverse Curl',
  'Cable Reverse Curl',
  'Drag Curl',
  'Concentration Curl',
  'Hammer Curl',
  'Cross-Body Hammer Curl',
  'Rope Hammer Curl',
  // Triceps
  'Triceps Pushdown',
  'Rope Triceps Pushdown',
  'Straight Bar Triceps Pushdown',
  'Reverse-Grip Triceps Pushdown',
  'Overhead Cable Triceps Extension',
  'Single-Arm Cable Triceps Extension',
  'Dumbbell Overhead Triceps Extension',
  'Barbell Overhead Triceps Extension',
  'Skull Crusher',
  'EZ Bar Skull Crusher',
  'Lying Dumbbell Triceps Extension',
  'Close-Grip Push-Up',
  'Close-Grip Smith Machine Press',
  'Machine Dip',
  'Assisted Dip',
  // Forearms and grip
  'Wrist Curl',
  'Reverse Wrist Curl',
  'Behind-the-Back Wrist Curl',
  'Cable Wrist Curl',
  'Farmer Carry',
  'Suitcase Carry',
  'Plate Pinch Hold',
  'Dead Hang',
  'Weighted Dead Hang',
  // Core
  'Cable Crunch',
  'Machine Crunch',
  'Weighted Crunch',
  'Decline Sit-Up',
  'Roman Chair Sit-Up',
  'Ab Wheel Rollout',
  'Hanging Knee Raise',
  'Hanging Leg Raise',
  'Captain Chair Leg Raise',
  'Toes to Bar',
  'Reverse Crunch',
  'V-Up',
  'Dead Bug',
  'Bird Dog',
  'Plank',
  'Weighted Plank',
  'Side Plank',
  'RKC Plank',
  'Pallof Press',
  'Cable Wood Chop',
  'Landmine Rotation',
  'Russian Twist',
  'Weighted Russian Twist',
  'Back Extension Hold',
  // Full body and conditioning
  'Barbell Clean',
  'Power Clean',
  'Hang Clean',
  'Clean and Press',
  'Barbell Snatch',
  'Kettlebell Swing',
  'Single-Arm Kettlebell Swing',
  'Thruster',
  'Wall Ball',
  'Battle Rope Waves',
  'Sled Push',
  'Sled Pull',
  'Prowler Push',
  'Rowing Machine',
  'Air Bike',
  'Ski Erg',
  'Stair Climber',
  'Treadmill Incline Walk',
  'Elliptical',
] as const

const DEFAULT_EXERCISE_ALIAS_MAP: Readonly<Record<string, string>> = {
  'bench press': 'Barbell Bench Press',
  'bb bench': 'Barbell Bench Press',
  'barbell bench': 'Barbell Bench Press',
  'incline bench': 'Incline Barbell Bench Press',
  'db incline press': 'Incline Dumbbell Press',
  'ohp': 'Overhead Press',
  'military press': 'Overhead Press',
  'lat raise': 'Lateral Raise',
  'side raise': 'Lateral Raise',
  'rear delt flyes': 'Rear Delt Fly',
  'pull up': 'Pull-Up',
  'chin up': 'Chin-Up',
  'pullups': 'Pull-Up',
  'chinups': 'Chin-Up',
  'lat pull down': 'Lat Pulldown',
  'pulldown': 'Lat Pulldown',
  'cable row': 'Seated Cable Row',
  'bb squat': 'Back Squat',
  'rdl': 'Romanian Deadlift',
  'trap deadlift': 'Trap Bar Deadlift',
  'leg ext': 'Leg Extension',
  'leg extension machine': 'Leg Extension',
  'leg curl machine': 'Leg Curl',
  lunges: 'Walking Lunge',
  'hip thrusts': 'Hip Thrust',
  'calf raise': 'Standing Calf Raise',
  'bb curl': 'Barbell Curl',
  'db curl': 'Dumbbell Curl',
  'hammer curls': 'Hammer Curl',
  'tricep pushdown': 'Triceps Pushdown',
  'triceps extension': 'Overhead Cable Triceps Extension',
  'skull crushers': 'Skull Crusher',
  crunches: 'Cable Crunch',
  planks: 'Plank',
  'pec deck': 'Pec Deck Fly',
  'chest press machine': 'Machine Chest Press',
  'shoulder press machine': 'Machine Shoulder Press',
  'hack squat machine': 'Machine Hack Squat',
  'hamstring curl': 'Leg Curl',
  'leg press machine': 'Leg Press',
  'abductor machine': 'Machine Hip Abduction',
  'adductor machine': 'Machine Hip Adduction',
}

function toExerciseLookupKey(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFKD')
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ')
}

const BASE_EXERCISE_LOOKUP = (() => {
  const lookup = new Map<string, string>()

  for (const name of DEFAULT_EXERCISE_NAMES) {
    lookup.set(toExerciseLookupKey(name), name)
  }

  for (const [alias, canonical] of Object.entries(DEFAULT_EXERCISE_ALIAS_MAP)) {
    lookup.set(toExerciseLookupKey(alias), canonical)
  }

  return lookup
})()

export function resolveCanonicalExerciseName(
  input: string,
  additionalNames: readonly string[] = [],
): string {
  const trimmed = input.trim()
  if (!trimmed) return ''

  const key = toExerciseLookupKey(trimmed)
  const baseMatch = BASE_EXERCISE_LOOKUP.get(key)
  if (baseMatch) return baseMatch

  for (const name of additionalNames) {
    if (toExerciseLookupKey(name) === key) return name
  }

  return trimmed
}
